name: geoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - myst-parser
  - python=3.11.13
  - black
  - pytest-asyncio
  - aiohttp
  - pytest
  - sphinx
  - geopandas
prefix: /opt/miniconda3/envs/geoenv
