name: geoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - attrs=25.4.0
  - babel=2.17.0
  - backports.asyncio.runner=1.2.0
  - backports.zstd=1.3.0
  - black=26.1.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - docutils=0.22.4
  - exceptiongroup=1.3.1
  - folium=0.20.0
  - fonttools=4.61.1
  - freetype=2.14.1
  - freexl=2.0.0
  - frozenlist=1.7.0
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geos=3.14.1
  - giflib=5.2.2
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - imagesize=1.4.1
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - joblib=1.5.3
  - json-c=0.18
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - lerc=4.0.0
  - libarchive=3.8.5
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.18.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-core=3.12.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.54
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - minizip=4.0.10
  - multidict=6.7.0
  - munkres=1.1.4
  - muparser=2.3.5
  - mypy_extensions=1.1.0
  - myst-parser=5.0.0
  - ncurses=6.5
  - networkx=3.6.1
  - numpy=2.4.2
  - openjpeg=2.5.4
  - openssl=3.6.1
  - packaging=26.0
  - pandas=3.0.0
  - pathspec=1.0.4
  - pcre2=10.47
  - pillow=12.1.0
  - pip=26.0
  - platformdirs=4.5.1
  - pluggy=1.6.0
  - proj=9.7.1
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pygments=2.19.2
  - pyogrio=0.12.1
  - pyparsing=3.3.2
  - pyproj=3.7.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - pytest-asyncio=1.3.0
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytokens=0.4.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - readline=8.3
  - requests=2.32.5
  - roman-numerals=4.1.0
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - setuptools=80.10.2
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - snowballstemmer=3.0.1
  - sphinx=9.0.4
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.51.2
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.6.3
  - wheel=0.46.3
  - xerces-c=3.3.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/geoenv
